# add the below section to `.cargo/config.toml`

[target.'cfg(all())']
rustflags = [
    # BEGIN - Embark standard lints v6 for Rust 1.55+
    # do not change or add/remove here, but one can add exceptions after this section
    # for more info see: <https://github.com/EmbarkStudios/rust-ecosystem/issues/59>
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wclippy::await_holding_lock",
    "-Wclippy::char_lit_as_u8",
    "-Wclippy::checked_conversions",
    "-Wclippy::dbg_macro",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::doc_markdown",
    "-Wclippy::empty_enum",
    "-Wclippy::enum_glob_use",
    "-Wclippy::exit",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::float_cmp_const",
    "-Wclippy::fn_params_excessive_bools",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::if_let_mutex",
    "-Wclippy::implicit_clone",
    "-Wclippy::imprecise_flops",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::large_digit_groups",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::let_unit_value",
    "-Wclippy::linkedlist",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_ok_or",
    "-Wclippy::map_err_ignore",
    "-Wclippy::map_flatten",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::mem_forget",
    "-Wclippy::mismatched_target_os",
    "-Wclippy::missing_enforced_import_renames",
    "-Wclippy::mut_mut",
    "-Wclippy::mutex_integer",
    "-Wclippy::needless_borrow",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::option_option",
    "-Wclippy::path_buf_push_overwrite",
    "-Wclippy::ptr_as_ptr",
    "-Wclippy::rc_mutex",
    "-Wclippy::ref_option_ref",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::single_match_else",
    "-Aclippy::string_add_assign",
    "-Aclippy::string_add",
    "-Wclippy::string_lit_as_bytes",
    "-Wclippy::string_to_string",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unused_self",
    "-Wclippy::useless_transmute",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::zero_sized_map_values",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    # END - Embark standard lints v6 for Rust 1.55+
    "-Wclippy::pedantic",
    "-Aclippy::must_use_candidate",
    "-Aclippy::missing_errors_doc",
    "-Wclippy::unwrap_used",
    "-Wclippy::nursery",
    "-Wabsolute_paths_not_starting_with_crate",
    "-Welided_lifetimes_in_paths",
    "-Wexplicit_outlives_requirements",
    "-Wkeyword_idents",
    "-Wmacro_use_extern_crate",
    "-Wmeta_variable_misuse",
    "-Wmissing_abi",
    "-Wmissing_copy_implementations",
    "-Wmissing_debug_implementations",
    "-Wnon_ascii_idents",
    "-Wnoop_method_call",
    "-Wrust_2021_incompatible_closure_captures",
    "-Wrust_2021_incompatible_or_patterns",
    "-Wrust_2021_prefixes_incompatible_syntax",
    "-Wrust_2021_prelude_collisions",
    "-Wsingle_use_lifetimes",
    "-Wtrivial_casts",
    "-Wtrivial_numeric_casts",
    "-Wunsafe_code",
    "-Wunsafe_op_in_unsafe_fn",
    "-Wunstable_features",
    "-Wunused_extern_crates",
    "-Wunused_import_braces",
    "-Wunused_lifetimes",
    "-Wunused_macro_rules",
    "-Wunused_qualifications",
    "-Wunused_results",
    "-Aclippy::module-name-repetitions",
    "-Wvariant_size_differences",
    "-Wclippy::manual_let_else",
    "-Wclippy::bool_to_int_with_if",
    "-Wclippy::manual_range_contains",
    "-Wclippy::match_like_matches_macro",
    "-Wclippy::needless_doctest_main",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::similar_names",
    "-Wclippy::uninlined_format_args",
    "-Wclippy::unwrap_or_default",
]
